name: BetterRewards
main: fernanACM\BetterRewards\BetterRewards
version: 2.0.0
api: 5.0.0
author: fernanACM
description: "Daily and monthly rewards, depending on the day of the week. Available for PocketMine-MP 5.0 servers"
website: https://github.com/fernanACM

permissions:
  betterrewards.cmd.acm:
    default: true
  betterrewards.edit.acm:
    default: op
  betterrewards.monthly.acm:
    default: true
  betterrewards.diary.acm:
    default: true